import Head from "next/head"
import router from "next/router"
import useSession from "../../hooks/useSession"
import Spinner from "../lib/spinner"

export default function Layout({ children }: { children: React.ReactNode }) {
  const { org, status } = useSession();

  if (status !== 'authenticated' || !org) {
    // status could be 'loading' or 'unauthenticated'
    if (status === 'unauthenticated') {
      // redirect to login page
      router.push('/auth/signin');
    }
    // loading state
    return (
      <>
        <Head>
          <title>Owl Console</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>
          <meta name="author" content="Owl"></meta>
          <link rel="icon" href="/images/favicon.ico" />
        </Head>

        <div className="flex w-screen h-screen items-center justify-center bg-landing bg-cover">
          <Spinner />
        </div>
      </>
    );
  }

  return <>Welcome to Owl Console</>
}