import type { NextPage } from 'next'
import Head from 'next/head'

const SignIn: NextPage = () => {
  return (
    <>
      <Head>
        <title>Sign In | Owl Console</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Hello World!</h1>
    </>
  )
}

export default SignIn
