import Head from 'next/head'
import Layout from '../components/layout'
import { NextPageWithLayout } from '../typescript/nextpage'

const Home: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Owl Console</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/favicon.ico" />
      </Head>

      <h1>Hello World!</h1>
    </>
  )
}

// return the Home page wrapped in the Layout component
Home.getLayout = function getLayout(page: React.ReactElement) {
  return <Layout>{page}</Layout>;
}

export default Home
