import Head from 'next/head'
import router from 'next/router'
import Spinner from '../components/lib/spinner'
import useSession from '../hooks/useSession'
import { NextPageWithLayout } from '../typescript/nextpage'

const Home: NextPageWithLayout = () => {
  const { status } = useSession();

  // status could be 'loading' or 'unauthenticated'
  if (status === 'unauthenticated') {
    // redirect to login page
    router.push('/auth/signin');
  }
  else if (status === 'authenticated') {
    // redirect to dashboard
    router.push('/dashboard');
  }

  return (
    <>
      <Head>
        <title>Owl Console</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>
        <meta name="author" content="Owl"></meta>
        <link rel="icon" href="/images/favicon.ico" />
      </Head>

      <div className="flex w-screen h-screen items-center justify-center bg-landing bg-cover">
        <Spinner />
      </div>
    </>
  );
}

export default Home