import Head from 'next/head'
import { useState } from 'react'
import KeyDisplay from '../../components/home/key_display'
import Layout from '../../components/layout'
import useSession from '../../hooks/useSession'
import { NextPageWithLayout } from '../../typescript/nextpage'

const Home: NextPageWithLayout = () => {
  const { data } = useSession();
  const [admins, setAdmins] = useState<any[]>(data.admins);

  if (!data) {
    return (
      <>
        <h6 className="text-gray-text mt-8">Your Authentication Key:</h6>

        <div className="flex flex-col mt-4 gap-x-4">
          <div className="rounded-xl bg-gray-bg animate-pulse w-full h-20"></div>
          <div className="mt-6 rounded-xl bg-gray-bg animate-pulse w-full h-16"></div>
        </div>

        <h6 className="text-gray-text mt-8">Appointed Admins:</h6>
        <div className="rounded-xl bg-gray-bg animate-pulse w-full h-48 mt-4"></div>

        <h6 className="text-gray-text mt-8">Admin Management:</h6>
        <div className="rounded-xl bg-gray-bg animate-pulse w-full h-20 mt-4"></div>
      </>
    )
  }

  return (
    <div className="pb-10">
      <Head>
        <title>Owl Console</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/favicon.ico" />
      </Head>

      <h6 className="text-gray-text mt-8">Your Authentication Key:</h6>

      <div className="flex flex-col mt-4 gap-x-4">
        <KeyDisplay key={data.credentials.key} />

        <button className="px-5 py-3 border-2 border-primary rounded-xl mt-6">
          <h5>Reset credentials</h5>
        </button>
      </div>

      {/* <h6 className="text-gray-text mt-8">Appointed Admins:</h6>

      { admins.length === 0 ? (
          <h6 className="w-full text-center mt-6">Your organization has not appointed any admins yet.</h6>
        ) : (
          <p className="text-red-500 mb-6">Deleting an admin also deletes resources managed by that admin.</p>
        )
      }

      {admins.map((user: any) => (
        <AdminCell key={user.id} user={user} />
      ))}

      <h6 className="text-gray-text mt-8">Add new Admins:</h6> */}
    </div>
  )
}

// return the Home page wrapped in the Layout component
Home.getLayout = function getLayout(page: React.ReactElement) {
  return <Layout>{page}</Layout>;
}

export default Home
